// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/insights.dart';
import 'api/llm.dart';
import 'api/ops.dart';
import 'api/scan.dart';
import 'api/system.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<ScanProgress> dco_decode_StreamSink_scan_progress_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AiRecommendation dco_decode_ai_recommendation(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DiskSpace dco_decode_box_autoadd_disk_space(dynamic raw);

  @protected
  FsNode dco_decode_box_autoadd_fs_node(dynamic raw);

  @protected
  LlmSettings dco_decode_box_autoadd_llm_settings(dynamic raw);

  @protected
  UiPrefs dco_decode_box_autoadd_ui_prefs(dynamic raw);

  @protected
  DiskSpace dco_decode_disk_space(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FdaStatus dco_decode_fda_status(dynamic raw);

  @protected
  FsKind dco_decode_fs_kind(dynamic raw);

  @protected
  FsNode dco_decode_fs_node(dynamic raw);

  @protected
  FsTier dco_decode_fs_tier(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Insight dco_decode_insight(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AiRecommendation> dco_decode_list_ai_recommendation(dynamic raw);

  @protected
  List<FsNode> dco_decode_list_fs_node(dynamic raw);

  @protected
  List<Insight> dco_decode_list_insight(dynamic raw);

  @protected
  List<Location> dco_decode_list_location(dynamic raw);

  @protected
  List<OpOutcome> dco_decode_list_op_outcome(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  LlmSettings dco_decode_llm_settings(dynamic raw);

  @protected
  Location dco_decode_location(dynamic raw);

  @protected
  OpOutcome dco_decode_op_outcome(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DiskSpace? dco_decode_opt_box_autoadd_disk_space(dynamic raw);

  @protected
  FsNode? dco_decode_opt_box_autoadd_fs_node(dynamic raw);

  @protected
  ScanProgress dco_decode_scan_progress(dynamic raw);

  @protected
  ScanStage dco_decode_scan_stage(dynamic raw);

  @protected
  SortKey dco_decode_sort_key(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiPrefs dco_decode_ui_prefs(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateCheck dco_decode_update_check(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<ScanProgress> sse_decode_StreamSink_scan_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AiRecommendation sse_decode_ai_recommendation(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DiskSpace sse_decode_box_autoadd_disk_space(SseDeserializer deserializer);

  @protected
  FsNode sse_decode_box_autoadd_fs_node(SseDeserializer deserializer);

  @protected
  LlmSettings sse_decode_box_autoadd_llm_settings(SseDeserializer deserializer);

  @protected
  UiPrefs sse_decode_box_autoadd_ui_prefs(SseDeserializer deserializer);

  @protected
  DiskSpace sse_decode_disk_space(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FdaStatus sse_decode_fda_status(SseDeserializer deserializer);

  @protected
  FsKind sse_decode_fs_kind(SseDeserializer deserializer);

  @protected
  FsNode sse_decode_fs_node(SseDeserializer deserializer);

  @protected
  FsTier sse_decode_fs_tier(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Insight sse_decode_insight(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AiRecommendation> sse_decode_list_ai_recommendation(
    SseDeserializer deserializer,
  );

  @protected
  List<FsNode> sse_decode_list_fs_node(SseDeserializer deserializer);

  @protected
  List<Insight> sse_decode_list_insight(SseDeserializer deserializer);

  @protected
  List<Location> sse_decode_list_location(SseDeserializer deserializer);

  @protected
  List<OpOutcome> sse_decode_list_op_outcome(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  LlmSettings sse_decode_llm_settings(SseDeserializer deserializer);

  @protected
  Location sse_decode_location(SseDeserializer deserializer);

  @protected
  OpOutcome sse_decode_op_outcome(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DiskSpace? sse_decode_opt_box_autoadd_disk_space(
    SseDeserializer deserializer,
  );

  @protected
  FsNode? sse_decode_opt_box_autoadd_fs_node(SseDeserializer deserializer);

  @protected
  ScanProgress sse_decode_scan_progress(SseDeserializer deserializer);

  @protected
  ScanStage sse_decode_scan_stage(SseDeserializer deserializer);

  @protected
  SortKey sse_decode_sort_key(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiPrefs sse_decode_ui_prefs(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateCheck sse_decode_update_check(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_scan_progress_Sse(
    RustStreamSink<ScanProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ai_recommendation(
    AiRecommendation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_disk_space(
    DiskSpace self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_fs_node(FsNode self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_llm_settings(
    LlmSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_prefs(UiPrefs self, SseSerializer serializer);

  @protected
  void sse_encode_disk_space(DiskSpace self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fda_status(FdaStatus self, SseSerializer serializer);

  @protected
  void sse_encode_fs_kind(FsKind self, SseSerializer serializer);

  @protected
  void sse_encode_fs_node(FsNode self, SseSerializer serializer);

  @protected
  void sse_encode_fs_tier(FsTier self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_insight(Insight self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ai_recommendation(
    List<AiRecommendation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_fs_node(List<FsNode> self, SseSerializer serializer);

  @protected
  void sse_encode_list_insight(List<Insight> self, SseSerializer serializer);

  @protected
  void sse_encode_list_location(List<Location> self, SseSerializer serializer);

  @protected
  void sse_encode_list_op_outcome(
    List<OpOutcome> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_llm_settings(LlmSettings self, SseSerializer serializer);

  @protected
  void sse_encode_location(Location self, SseSerializer serializer);

  @protected
  void sse_encode_op_outcome(OpOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_disk_space(
    DiskSpace? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_fs_node(
    FsNode? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scan_progress(ScanProgress self, SseSerializer serializer);

  @protected
  void sse_encode_scan_stage(ScanStage self, SseSerializer serializer);

  @protected
  void sse_encode_sort_key(SortKey self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_prefs(UiPrefs self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_check(UpdateCheck self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
