// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/insights.dart';
import 'api/llm.dart';
import 'api/ops.dart';
import 'api/scan.dart';
import 'api/system.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiScanInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1396345355;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_clean_mind',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiScanCancelScan();

  Future<UpdateCheck> crateApiSystemCheckForUpdate({
    required String currentVersion,
  });

  String crateApiScanDefaultScanRoot();

  Future<List<OpOutcome>> crateApiOpsDeletePermanently({
    required Int64List nodeIds,
    required bool confirmed,
  });

  FdaStatus crateApiSystemFullDiskAccessStatus();

  List<FsNode> crateApiScanGetChildren({
    required PlatformInt64 id,
    required PlatformInt64 limit,
  });

  List<FsNode> crateApiScanGetChildrenSorted({
    required PlatformInt64 id,
    required SortKey key,
    required bool ascending,
    required PlatformInt64 limit,
  });

  List<Insight> crateApiInsightsGetInsights();

  LlmSettings crateApiLlmGetLlmSettings();

  FsNode? crateApiScanGetNode({required PlatformInt64 id});

  UiPrefs crateApiSystemGetUiPrefs();

  bool crateApiLlmHasApiKey({required String provider});

  String crateApiScanHomeDirPath();

  Future<void> crateApiScanInitApp();

  Future<List<OpOutcome>> crateApiOpsMoveToTrash({required Int64List nodeIds});

  List<FsNode> crateApiScanNodeAncestry({required PlatformInt64 id});

  void crateApiSystemOpenFullDiskAccessSettings();

  void crateApiOpsOpenItem({required PlatformInt64 nodeId});

  void crateApiSystemOpenTrash();

  void crateApiSystemOpenUrl({required String url});

  List<String> crateApiScanRecentScanRoots();

  void crateApiOpsRevealInFileManager({required PlatformInt64 nodeId});

  Future<List<AiRecommendation>> crateApiLlmRunAiAnalysis();

  void crateApiLlmSaveApiKey({required String provider, required String key});

  List<String> crateApiScanScanSkippedPaths();

  List<FsNode> crateApiScanSearchNodes({
    required String query,
    required PlatformInt64 limit,
  });

  void crateApiLlmSetLlmSettings({required LlmSettings settings});

  void crateApiScanSetScanRoot({required String path});

  void crateApiSystemSetUiPrefs({required UiPrefs prefs});

  LlmSettings crateApiLlmSettingsForProvider({required String provider});

  List<Location> crateApiSystemStandardLocations();

  Stream<ScanProgress> crateApiScanStartScan({required String path});

  Future<String> crateApiLlmTestLlmConnection();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiScanCancelScan() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScanCancelScanConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanCancelScanConstMeta =>
      const TaskConstMeta(debugName: "cancel_scan", argNames: []);

  @override
  Future<UpdateCheck> crateApiSystemCheckForUpdate({
    required String currentVersion,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(currentVersion, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_update_check,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSystemCheckForUpdateConstMeta,
        argValues: [currentVersion],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSystemCheckForUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "check_for_update",
        argNames: ["currentVersion"],
      );

  @override
  String crateApiScanDefaultScanRoot() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScanDefaultScanRootConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanDefaultScanRootConstMeta =>
      const TaskConstMeta(debugName: "default_scan_root", argNames: []);

  @override
  Future<List<OpOutcome>> crateApiOpsDeletePermanently({
    required Int64List nodeIds,
    required bool confirmed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_i_64_strict(nodeIds, serializer);
          sse_encode_bool(confirmed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_op_outcome,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiOpsDeletePermanentlyConstMeta,
        argValues: [nodeIds, confirmed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpsDeletePermanentlyConstMeta =>
      const TaskConstMeta(
        debugName: "delete_permanently",
        argNames: ["nodeIds", "confirmed"],
      );

  @override
  FdaStatus crateApiSystemFullDiskAccessStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_fda_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSystemFullDiskAccessStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSystemFullDiskAccessStatusConstMeta =>
      const TaskConstMeta(debugName: "full_disk_access_status", argNames: []);

  @override
  List<FsNode> crateApiScanGetChildren({
    required PlatformInt64 id,
    required PlatformInt64 limit,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          sse_encode_i_64(limit, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_fs_node,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScanGetChildrenConstMeta,
        argValues: [id, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanGetChildrenConstMeta =>
      const TaskConstMeta(debugName: "get_children", argNames: ["id", "limit"]);

  @override
  List<FsNode> crateApiScanGetChildrenSorted({
    required PlatformInt64 id,
    required SortKey key,
    required bool ascending,
    required PlatformInt64 limit,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          sse_encode_sort_key(key, serializer);
          sse_encode_bool(ascending, serializer);
          sse_encode_i_64(limit, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_fs_node,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScanGetChildrenSortedConstMeta,
        argValues: [id, key, ascending, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanGetChildrenSortedConstMeta =>
      const TaskConstMeta(
        debugName: "get_children_sorted",
        argNames: ["id", "key", "ascending", "limit"],
      );

  @override
  List<Insight> crateApiInsightsGetInsights() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_insight,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInsightsGetInsightsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInsightsGetInsightsConstMeta =>
      const TaskConstMeta(debugName: "get_insights", argNames: []);

  @override
  LlmSettings crateApiLlmGetLlmSettings() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_llm_settings,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLlmGetLlmSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLlmGetLlmSettingsConstMeta =>
      const TaskConstMeta(debugName: "get_llm_settings", argNames: []);

  @override
  FsNode? crateApiScanGetNode({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_fs_node,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScanGetNodeConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanGetNodeConstMeta =>
      const TaskConstMeta(debugName: "get_node", argNames: ["id"]);

  @override
  UiPrefs crateApiSystemGetUiPrefs() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ui_prefs,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSystemGetUiPrefsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSystemGetUiPrefsConstMeta =>
      const TaskConstMeta(debugName: "get_ui_prefs", argNames: []);

  @override
  bool crateApiLlmHasApiKey({required String provider}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(provider, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLlmHasApiKeyConstMeta,
        argValues: [provider],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLlmHasApiKeyConstMeta =>
      const TaskConstMeta(debugName: "has_api_key", argNames: ["provider"]);

  @override
  String crateApiScanHomeDirPath() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScanHomeDirPathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanHomeDirPathConstMeta =>
      const TaskConstMeta(debugName: "home_dir_path", argNames: []);

  @override
  Future<void> crateApiScanInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScanInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<OpOutcome>> crateApiOpsMoveToTrash({required Int64List nodeIds}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_i_64_strict(nodeIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_op_outcome,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiOpsMoveToTrashConstMeta,
        argValues: [nodeIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpsMoveToTrashConstMeta =>
      const TaskConstMeta(debugName: "move_to_trash", argNames: ["nodeIds"]);

  @override
  List<FsNode> crateApiScanNodeAncestry({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_fs_node,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScanNodeAncestryConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanNodeAncestryConstMeta =>
      const TaskConstMeta(debugName: "node_ancestry", argNames: ["id"]);

  @override
  void crateApiSystemOpenFullDiskAccessSettings() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSystemOpenFullDiskAccessSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSystemOpenFullDiskAccessSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "open_full_disk_access_settings",
        argNames: [],
      );

  @override
  void crateApiOpsOpenItem({required PlatformInt64 nodeId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(nodeId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiOpsOpenItemConstMeta,
        argValues: [nodeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpsOpenItemConstMeta =>
      const TaskConstMeta(debugName: "open_item", argNames: ["nodeId"]);

  @override
  void crateApiSystemOpenTrash() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSystemOpenTrashConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSystemOpenTrashConstMeta =>
      const TaskConstMeta(debugName: "open_trash", argNames: []);

  @override
  void crateApiSystemOpenUrl({required String url}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSystemOpenUrlConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSystemOpenUrlConstMeta =>
      const TaskConstMeta(debugName: "open_url", argNames: ["url"]);

  @override
  List<String> crateApiScanRecentScanRoots() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScanRecentScanRootsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanRecentScanRootsConstMeta =>
      const TaskConstMeta(debugName: "recent_scan_roots", argNames: []);

  @override
  void crateApiOpsRevealInFileManager({required PlatformInt64 nodeId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(nodeId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiOpsRevealInFileManagerConstMeta,
        argValues: [nodeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpsRevealInFileManagerConstMeta =>
      const TaskConstMeta(
        debugName: "reveal_in_file_manager",
        argNames: ["nodeId"],
      );

  @override
  Future<List<AiRecommendation>> crateApiLlmRunAiAnalysis() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ai_recommendation,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLlmRunAiAnalysisConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLlmRunAiAnalysisConstMeta =>
      const TaskConstMeta(debugName: "run_ai_analysis", argNames: []);

  @override
  void crateApiLlmSaveApiKey({required String provider, required String key}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(provider, serializer);
          sse_encode_String(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLlmSaveApiKeyConstMeta,
        argValues: [provider, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLlmSaveApiKeyConstMeta => const TaskConstMeta(
    debugName: "save_api_key",
    argNames: ["provider", "key"],
  );

  @override
  List<String> crateApiScanScanSkippedPaths() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScanScanSkippedPathsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanScanSkippedPathsConstMeta =>
      const TaskConstMeta(debugName: "scan_skipped_paths", argNames: []);

  @override
  List<FsNode> crateApiScanSearchNodes({
    required String query,
    required PlatformInt64 limit,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_i_64(limit, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_fs_node,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScanSearchNodesConstMeta,
        argValues: [query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanSearchNodesConstMeta => const TaskConstMeta(
    debugName: "search_nodes",
    argNames: ["query", "limit"],
  );

  @override
  void crateApiLlmSetLlmSettings({required LlmSettings settings}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_llm_settings(settings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLlmSetLlmSettingsConstMeta,
        argValues: [settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLlmSetLlmSettingsConstMeta => const TaskConstMeta(
    debugName: "set_llm_settings",
    argNames: ["settings"],
  );

  @override
  void crateApiScanSetScanRoot({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScanSetScanRootConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanSetScanRootConstMeta =>
      const TaskConstMeta(debugName: "set_scan_root", argNames: ["path"]);

  @override
  void crateApiSystemSetUiPrefs({required UiPrefs prefs}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ui_prefs(prefs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSystemSetUiPrefsConstMeta,
        argValues: [prefs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSystemSetUiPrefsConstMeta =>
      const TaskConstMeta(debugName: "set_ui_prefs", argNames: ["prefs"]);

  @override
  LlmSettings crateApiLlmSettingsForProvider({required String provider}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(provider, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_llm_settings,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLlmSettingsForProviderConstMeta,
        argValues: [provider],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLlmSettingsForProviderConstMeta =>
      const TaskConstMeta(
        debugName: "settings_for_provider",
        argNames: ["provider"],
      );

  @override
  List<Location> crateApiSystemStandardLocations() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_location,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSystemStandardLocationsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSystemStandardLocationsConstMeta =>
      const TaskConstMeta(debugName: "standard_locations", argNames: []);

  @override
  Stream<ScanProgress> crateApiScanStartScan({required String path}) {
    final sink = RustStreamSink<ScanProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(path, serializer);
            sse_encode_StreamSink_scan_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 32,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiScanStartScanConstMeta,
          argValues: [path, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiScanStartScanConstMeta =>
      const TaskConstMeta(debugName: "start_scan", argNames: ["path", "sink"]);

  @override
  Future<String> crateApiLlmTestLlmConnection() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLlmTestLlmConnectionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLlmTestLlmConnectionConstMeta =>
      const TaskConstMeta(debugName: "test_llm_connection", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<ScanProgress> dco_decode_StreamSink_scan_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AiRecommendation dco_decode_ai_recommendation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AiRecommendation(
      nodeId: dco_decode_i_64(arr[0]),
      path: dco_decode_String(arr[1]),
      size: dco_decode_i_64(arr[2]),
      verdict: dco_decode_String(arr[3]),
      regenerability: dco_decode_String(arr[4]),
      reasoning: dco_decode_String(arr[5]),
      confidence: dco_decode_f_64(arr[6]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FsNode dco_decode_box_autoadd_fs_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_fs_node(raw);
  }

  @protected
  LlmSettings dco_decode_box_autoadd_llm_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_llm_settings(raw);
  }

  @protected
  UiPrefs dco_decode_box_autoadd_ui_prefs(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ui_prefs(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FdaStatus dco_decode_fda_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FdaStatus.values[raw as int];
  }

  @protected
  FsKind dco_decode_fs_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FsKind.values[raw as int];
  }

  @protected
  FsNode dco_decode_fs_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return FsNode(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      path: dco_decode_String(arr[2]),
      kind: dco_decode_fs_kind(arr[3]),
      size: dco_decode_i_64(arr[4]),
      logicalSize: dco_decode_i_64(arr[5]),
      mtime: dco_decode_i_64(arr[6]),
      fileCount: dco_decode_i_64(arr[7]),
      dirCount: dco_decode_i_64(arr[8]),
      itemCount: dco_decode_i_64(arr[9]),
      childCount: dco_decode_i_64(arr[10]),
      tier: dco_decode_fs_tier(arr[11]),
      ruleId: dco_decode_opt_String(arr[12]),
      ruleName: dco_decode_opt_String(arr[13]),
      category: dco_decode_opt_String(arr[14]),
    );
  }

  @protected
  FsTier dco_decode_fs_tier(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FsTier.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Insight dco_decode_insight(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return Insight(
      nodeId: dco_decode_i_64(arr[0]),
      path: dco_decode_String(arr[1]),
      size: dco_decode_i_64(arr[2]),
      tier: dco_decode_fs_tier(arr[3]),
      ruleId: dco_decode_String(arr[4]),
      ruleName: dco_decode_String(arr[5]),
      category: dco_decode_String(arr[6]),
      regenerability: dco_decode_String(arr[7]),
      regenerateWith: dco_decode_opt_String(arr[8]),
      explanation: dco_decode_String(arr[9]),
      staleDays: dco_decode_i_64(arr[10]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AiRecommendation> dco_decode_list_ai_recommendation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ai_recommendation).toList();
  }

  @protected
  List<FsNode> dco_decode_list_fs_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_fs_node).toList();
  }

  @protected
  List<Insight> dco_decode_list_insight(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_insight).toList();
  }

  @protected
  List<Location> dco_decode_list_location(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_location).toList();
  }

  @protected
  List<OpOutcome> dco_decode_list_op_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_op_outcome).toList();
  }

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeInt64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  LlmSettings dco_decode_llm_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LlmSettings(
      provider: dco_decode_String(arr[0]),
      baseUrl: dco_decode_String(arr[1]),
      model: dco_decode_String(arr[2]),
      redact: dco_decode_bool(arr[3]),
    );
  }

  @protected
  Location dco_decode_location(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Location(
      label: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      kind: dco_decode_String(arr[2]),
      exists: dco_decode_bool(arr[3]),
    );
  }

  @protected
  OpOutcome dco_decode_op_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return OpOutcome(
      path: dco_decode_String(arr[0]),
      ok: dco_decode_bool(arr[1]),
      message: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  FsNode? dco_decode_opt_box_autoadd_fs_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_fs_node(raw);
  }

  @protected
  ScanProgress dco_decode_scan_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ScanProgress(
      stage: dco_decode_scan_stage(arr[0]),
      files: dco_decode_i_64(arr[1]),
      dirs: dco_decode_i_64(arr[2]),
      bytes: dco_decode_i_64(arr[3]),
      errors: dco_decode_i_64(arr[4]),
      currentPath: dco_decode_String(arr[5]),
      rootId: dco_decode_i_64(arr[6]),
    );
  }

  @protected
  ScanStage dco_decode_scan_stage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ScanStage.values[raw as int];
  }

  @protected
  SortKey dco_decode_sort_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SortKey.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  UiPrefs dco_decode_ui_prefs(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return UiPrefs(
      resultsView: dco_decode_String(arr[0]),
      sortKey: dco_decode_String(arr[1]),
      sortAscending: dco_decode_bool(arr[2]),
    );
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UpdateCheck dco_decode_update_check(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return UpdateCheck(
      current: dco_decode_String(arr[0]),
      latest: dco_decode_String(arr[1]),
      updateAvailable: dco_decode_bool(arr[2]),
      releaseUrl: dco_decode_String(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<ScanProgress> sse_decode_StreamSink_scan_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AiRecommendation sse_decode_ai_recommendation(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_i_64(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_size = sse_decode_i_64(deserializer);
    var var_verdict = sse_decode_String(deserializer);
    var var_regenerability = sse_decode_String(deserializer);
    var var_reasoning = sse_decode_String(deserializer);
    var var_confidence = sse_decode_f_64(deserializer);
    return AiRecommendation(
      nodeId: var_nodeId,
      path: var_path,
      size: var_size,
      verdict: var_verdict,
      regenerability: var_regenerability,
      reasoning: var_reasoning,
      confidence: var_confidence,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FsNode sse_decode_box_autoadd_fs_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_fs_node(deserializer));
  }

  @protected
  LlmSettings sse_decode_box_autoadd_llm_settings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_llm_settings(deserializer));
  }

  @protected
  UiPrefs sse_decode_box_autoadd_ui_prefs(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ui_prefs(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FdaStatus sse_decode_fda_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FdaStatus.values[inner];
  }

  @protected
  FsKind sse_decode_fs_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FsKind.values[inner];
  }

  @protected
  FsNode sse_decode_fs_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_kind = sse_decode_fs_kind(deserializer);
    var var_size = sse_decode_i_64(deserializer);
    var var_logicalSize = sse_decode_i_64(deserializer);
    var var_mtime = sse_decode_i_64(deserializer);
    var var_fileCount = sse_decode_i_64(deserializer);
    var var_dirCount = sse_decode_i_64(deserializer);
    var var_itemCount = sse_decode_i_64(deserializer);
    var var_childCount = sse_decode_i_64(deserializer);
    var var_tier = sse_decode_fs_tier(deserializer);
    var var_ruleId = sse_decode_opt_String(deserializer);
    var var_ruleName = sse_decode_opt_String(deserializer);
    var var_category = sse_decode_opt_String(deserializer);
    return FsNode(
      id: var_id,
      name: var_name,
      path: var_path,
      kind: var_kind,
      size: var_size,
      logicalSize: var_logicalSize,
      mtime: var_mtime,
      fileCount: var_fileCount,
      dirCount: var_dirCount,
      itemCount: var_itemCount,
      childCount: var_childCount,
      tier: var_tier,
      ruleId: var_ruleId,
      ruleName: var_ruleName,
      category: var_category,
    );
  }

  @protected
  FsTier sse_decode_fs_tier(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FsTier.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Insight sse_decode_insight(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_i_64(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_size = sse_decode_i_64(deserializer);
    var var_tier = sse_decode_fs_tier(deserializer);
    var var_ruleId = sse_decode_String(deserializer);
    var var_ruleName = sse_decode_String(deserializer);
    var var_category = sse_decode_String(deserializer);
    var var_regenerability = sse_decode_String(deserializer);
    var var_regenerateWith = sse_decode_opt_String(deserializer);
    var var_explanation = sse_decode_String(deserializer);
    var var_staleDays = sse_decode_i_64(deserializer);
    return Insight(
      nodeId: var_nodeId,
      path: var_path,
      size: var_size,
      tier: var_tier,
      ruleId: var_ruleId,
      ruleName: var_ruleName,
      category: var_category,
      regenerability: var_regenerability,
      regenerateWith: var_regenerateWith,
      explanation: var_explanation,
      staleDays: var_staleDays,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AiRecommendation> sse_decode_list_ai_recommendation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AiRecommendation>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ai_recommendation(deserializer));
    }
    return ans_;
  }

  @protected
  List<FsNode> sse_decode_list_fs_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FsNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_fs_node(deserializer));
    }
    return ans_;
  }

  @protected
  List<Insight> sse_decode_list_insight(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Insight>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_insight(deserializer));
    }
    return ans_;
  }

  @protected
  List<Location> sse_decode_list_location(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Location>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_location(deserializer));
    }
    return ans_;
  }

  @protected
  List<OpOutcome> sse_decode_list_op_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OpOutcome>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_op_outcome(deserializer));
    }
    return ans_;
  }

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  LlmSettings sse_decode_llm_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_provider = sse_decode_String(deserializer);
    var var_baseUrl = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_redact = sse_decode_bool(deserializer);
    return LlmSettings(
      provider: var_provider,
      baseUrl: var_baseUrl,
      model: var_model,
      redact: var_redact,
    );
  }

  @protected
  Location sse_decode_location(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_label = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_exists = sse_decode_bool(deserializer);
    return Location(
      label: var_label,
      path: var_path,
      kind: var_kind,
      exists: var_exists,
    );
  }

  @protected
  OpOutcome sse_decode_op_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_ok = sse_decode_bool(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    return OpOutcome(path: var_path, ok: var_ok, message: var_message);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FsNode? sse_decode_opt_box_autoadd_fs_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_fs_node(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ScanProgress sse_decode_scan_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stage = sse_decode_scan_stage(deserializer);
    var var_files = sse_decode_i_64(deserializer);
    var var_dirs = sse_decode_i_64(deserializer);
    var var_bytes = sse_decode_i_64(deserializer);
    var var_errors = sse_decode_i_64(deserializer);
    var var_currentPath = sse_decode_String(deserializer);
    var var_rootId = sse_decode_i_64(deserializer);
    return ScanProgress(
      stage: var_stage,
      files: var_files,
      dirs: var_dirs,
      bytes: var_bytes,
      errors: var_errors,
      currentPath: var_currentPath,
      rootId: var_rootId,
    );
  }

  @protected
  ScanStage sse_decode_scan_stage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ScanStage.values[inner];
  }

  @protected
  SortKey sse_decode_sort_key(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SortKey.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  UiPrefs sse_decode_ui_prefs(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_resultsView = sse_decode_String(deserializer);
    var var_sortKey = sse_decode_String(deserializer);
    var var_sortAscending = sse_decode_bool(deserializer);
    return UiPrefs(
      resultsView: var_resultsView,
      sortKey: var_sortKey,
      sortAscending: var_sortAscending,
    );
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UpdateCheck sse_decode_update_check(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_current = sse_decode_String(deserializer);
    var var_latest = sse_decode_String(deserializer);
    var var_updateAvailable = sse_decode_bool(deserializer);
    var var_releaseUrl = sse_decode_String(deserializer);
    return UpdateCheck(
      current: var_current,
      latest: var_latest,
      updateAvailable: var_updateAvailable,
      releaseUrl: var_releaseUrl,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_scan_progress_Sse(
    RustStreamSink<ScanProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_scan_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_ai_recommendation(
    AiRecommendation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.nodeId, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_i_64(self.size, serializer);
    sse_encode_String(self.verdict, serializer);
    sse_encode_String(self.regenerability, serializer);
    sse_encode_String(self.reasoning, serializer);
    sse_encode_f_64(self.confidence, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_fs_node(FsNode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_fs_node(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_llm_settings(
    LlmSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_llm_settings(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ui_prefs(UiPrefs self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ui_prefs(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_fda_status(FdaStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_fs_kind(FsKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_fs_node(FsNode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_fs_kind(self.kind, serializer);
    sse_encode_i_64(self.size, serializer);
    sse_encode_i_64(self.logicalSize, serializer);
    sse_encode_i_64(self.mtime, serializer);
    sse_encode_i_64(self.fileCount, serializer);
    sse_encode_i_64(self.dirCount, serializer);
    sse_encode_i_64(self.itemCount, serializer);
    sse_encode_i_64(self.childCount, serializer);
    sse_encode_fs_tier(self.tier, serializer);
    sse_encode_opt_String(self.ruleId, serializer);
    sse_encode_opt_String(self.ruleName, serializer);
    sse_encode_opt_String(self.category, serializer);
  }

  @protected
  void sse_encode_fs_tier(FsTier self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_insight(Insight self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.nodeId, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_i_64(self.size, serializer);
    sse_encode_fs_tier(self.tier, serializer);
    sse_encode_String(self.ruleId, serializer);
    sse_encode_String(self.ruleName, serializer);
    sse_encode_String(self.category, serializer);
    sse_encode_String(self.regenerability, serializer);
    sse_encode_opt_String(self.regenerateWith, serializer);
    sse_encode_String(self.explanation, serializer);
    sse_encode_i_64(self.staleDays, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ai_recommendation(
    List<AiRecommendation> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ai_recommendation(item, serializer);
    }
  }

  @protected
  void sse_encode_list_fs_node(List<FsNode> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_fs_node(item, serializer);
    }
  }

  @protected
  void sse_encode_list_insight(List<Insight> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_insight(item, serializer);
    }
  }

  @protected
  void sse_encode_list_location(List<Location> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_location(item, serializer);
    }
  }

  @protected
  void sse_encode_list_op_outcome(
    List<OpOutcome> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_op_outcome(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_llm_settings(LlmSettings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.provider, serializer);
    sse_encode_String(self.baseUrl, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_bool(self.redact, serializer);
  }

  @protected
  void sse_encode_location(Location self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_bool(self.exists, serializer);
  }

  @protected
  void sse_encode_op_outcome(OpOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_String(self.message, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_fs_node(
    FsNode? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_fs_node(self, serializer);
    }
  }

  @protected
  void sse_encode_scan_progress(ScanProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_scan_stage(self.stage, serializer);
    sse_encode_i_64(self.files, serializer);
    sse_encode_i_64(self.dirs, serializer);
    sse_encode_i_64(self.bytes, serializer);
    sse_encode_i_64(self.errors, serializer);
    sse_encode_String(self.currentPath, serializer);
    sse_encode_i_64(self.rootId, serializer);
  }

  @protected
  void sse_encode_scan_stage(ScanStage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_sort_key(SortKey self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_ui_prefs(UiPrefs self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.resultsView, serializer);
    sse_encode_String(self.sortKey, serializer);
    sse_encode_bool(self.sortAscending, serializer);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_update_check(UpdateCheck self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.current, serializer);
    sse_encode_String(self.latest, serializer);
    sse_encode_bool(self.updateAvailable, serializer);
    sse_encode_String(self.releaseUrl, serializer);
  }
}
