// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'scan.dart';

/// Everything the rules engine flagged, largest first. Nested matches under
/// an already-flagged directory are excluded so sizes never double count.
List<Insight> getInsights() =>
    RustLib.instance.api.crateApiInsightsGetInsights();

class Insight {
  final PlatformInt64 nodeId;
  final String path;
  final PlatformInt64 size;
  final FsTier tier;
  final String ruleId;
  final String ruleName;
  final String category;
  final String regenerability;
  final String? regenerateWith;
  final String explanation;

  /// Days since the containing project (or the item itself) was touched;
  /// -1 when unknown.
  final PlatformInt64 staleDays;

  const Insight({
    required this.nodeId,
    required this.path,
    required this.size,
    required this.tier,
    required this.ruleId,
    required this.ruleName,
    required this.category,
    required this.regenerability,
    this.regenerateWith,
    required this.explanation,
    required this.staleDays,
  });

  @override
  int get hashCode =>
      nodeId.hashCode ^
      path.hashCode ^
      size.hashCode ^
      tier.hashCode ^
      ruleId.hashCode ^
      ruleName.hashCode ^
      category.hashCode ^
      regenerability.hashCode ^
      regenerateWith.hashCode ^
      explanation.hashCode ^
      staleDays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Insight &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          path == other.path &&
          size == other.size &&
          tier == other.tier &&
          ruleId == other.ruleId &&
          ruleName == other.ruleName &&
          category == other.category &&
          regenerability == other.regenerability &&
          regenerateWith == other.regenerateWith &&
          explanation == other.explanation &&
          staleDays == other.staleDays;
}
