// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `needs_key`

LlmSettings getLlmSettings() =>
    RustLib.instance.api.crateApiLlmGetLlmSettings();

void setLlmSettings({required LlmSettings settings}) =>
    RustLib.instance.api.crateApiLlmSetLlmSettings(settings: settings);

LlmSettings providerDefaults({required String provider}) =>
    RustLib.instance.api.crateApiLlmProviderDefaults(provider: provider);

/// Store the key in the OS keychain — never in config files. Empty deletes.
void saveApiKey({required String provider, required String key}) =>
    RustLib.instance.api.crateApiLlmSaveApiKey(provider: provider, key: key);

bool hasApiKey({required String provider}) =>
    RustLib.instance.api.crateApiLlmHasApiKey(provider: provider);

/// Round-trip a trivial prompt to verify provider settings and key.
Future<String> testLlmConnection() =>
    RustLib.instance.api.crateApiLlmTestLlmConnection();

/// Send the scan digest (metadata only) to the configured LLM and return
/// validated Tier-2 recommendations. The LLM can never promote anything to
/// Tier 1 and never touch protected paths — that is enforced here, not by
/// prompting.
Future<List<AiRecommendation>> runAiAnalysis() =>
    RustLib.instance.api.crateApiLlmRunAiAnalysis();

class AiRecommendation {
  final PlatformInt64 nodeId;
  final String path;
  final PlatformInt64 size;
  final String verdict;
  final String regenerability;
  final String reasoning;
  final double confidence;

  const AiRecommendation({
    required this.nodeId,
    required this.path,
    required this.size,
    required this.verdict,
    required this.regenerability,
    required this.reasoning,
    required this.confidence,
  });

  @override
  int get hashCode =>
      nodeId.hashCode ^
      path.hashCode ^
      size.hashCode ^
      verdict.hashCode ^
      regenerability.hashCode ^
      reasoning.hashCode ^
      confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiRecommendation &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          path == other.path &&
          size == other.size &&
          verdict == other.verdict &&
          regenerability == other.regenerability &&
          reasoning == other.reasoning &&
          confidence == other.confidence;
}

class LlmSettings {
  final String provider;
  final String baseUrl;
  final String model;
  final bool redact;

  const LlmSettings({
    required this.provider,
    required this.baseUrl,
    required this.model,
    required this.redact,
  });

  @override
  int get hashCode =>
      provider.hashCode ^ baseUrl.hashCode ^ model.hashCode ^ redact.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LlmSettings &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          redact == other.redact;
}
