// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `resolve_paths`, `run_delete`

/// Default deletion: recoverable, straight to the OS Trash / Recycle Bin.
Future<List<OpOutcome>> moveToTrash({required Int64List nodeIds}) =>
    RustLib.instance.api.crateApiOpsMoveToTrash(nodeIds: nodeIds);

/// Irreversible. The UI must gate this behind an explicit type-to-confirm
/// dialog; `confirmed` is re-checked here so no code path skips it.
Future<List<OpOutcome>> deletePermanently({
  required Int64List nodeIds,
  required bool confirmed,
}) => RustLib.instance.api.crateApiOpsDeletePermanently(
  nodeIds: nodeIds,
  confirmed: confirmed,
);

/// Show the item in Finder / Explorer / the file manager.
void revealInFileManager({required PlatformInt64 nodeId}) =>
    RustLib.instance.api.crateApiOpsRevealInFileManager(nodeId: nodeId);

/// Open the item with the OS default handler (file → default app,
/// directory → file manager).
void openItem({required PlatformInt64 nodeId}) =>
    RustLib.instance.api.crateApiOpsOpenItem(nodeId: nodeId);

class OpOutcome {
  final String path;
  final bool ok;
  final String? message;

  const OpOutcome({required this.path, required this.ok, this.message});

  @override
  int get hashCode => path.hashCode ^ ok.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpOutcome &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          ok == other.ok &&
          message == other.message;
}
