// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Scan a directory tree and return aggregate counts and allocated size.
/// Runs on a worker thread; the UI thread is never blocked.
Future<ScanSummary> scanSummary({required String path}) =>
    RustLib.instance.api.crateApiScanScanSummary(path: path);

/// Home directory of the current user, the default scan root.
String defaultScanRoot() => RustLib.instance.api.crateApiScanDefaultScanRoot();

/// Aggregate result of a scan, mirrored into Dart by flutter_rust_bridge.
class ScanSummary {
  final BigInt files;
  final BigInt dirs;
  final BigInt totalBytes;
  final BigInt errors;

  const ScanSummary({
    required this.files,
    required this.dirs,
    required this.totalBytes,
    required this.errors,
  });

  @override
  int get hashCode =>
      files.hashCode ^ dirs.hashCode ^ totalBytes.hashCode ^ errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanSummary &&
          runtimeType == other.runtimeType &&
          files == other.files &&
          dirs == other.dirs &&
          totalBytes == other.totalBytes &&
          errors == other.errors;
}
