// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `snapshot`, `to_fs_node`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Start a scan. Progress streams every ~120ms; the final item carries
/// `stage: Done` (with the root id) / `Cancelled` (with root id >= 0 if
/// partial results are available, -1 if this scan was superseded before it
/// could publish anything) / `Failed`.
Stream<ScanProgress> startScan({required String path}) =>
    RustLib.instance.api.crateApiScanStartScan(path: path);

Future<void> cancelScan() => RustLib.instance.api.crateApiScanCancelScan();

FsNode? getNode({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiScanGetNode(id: id);

/// Children of `id`, largest first. At most `limit` real entries; anything
/// beyond folds into a trailing `Rest` node so the UI stays bounded.
List<FsNode> getChildren({
  required PlatformInt64 id,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiScanGetChildren(id: id, limit: limit);

/// Children of `id` sorted by `key` (descending unless `ascending`), for the
/// list/table view. Like [`get_children`], anything past `limit` folds into a
/// trailing `Rest` node so the UI stays bounded.
List<FsNode> getChildrenSorted({
  required PlatformInt64 id,
  required SortKey key,
  required bool ascending,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiScanGetChildrenSorted(
  id: id,
  key: key,
  ascending: ascending,
  limit: limit,
);

/// Search the whole scan for nodes whose name contains `query`
/// (case-insensitive), largest first, capped at `limit`. Linear over the flat
/// arena — cheap even for a home-directory scan. The root and the synthetic
/// "(small files)" aggregates are excluded.
List<FsNode> searchNodes({
  required String query,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiScanSearchNodes(query: query, limit: limit);

/// Ancestry chain from the root down to `id`, inclusive (root first, `id`
/// last). Lets the UI rebuild the breadcrumb trail when jumping to an arbitrary
/// node (search hit, "largest items" tap). Empty if `id` isn't in the scan.
List<FsNode> nodeAncestry({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiScanNodeAncestry(id: id);

/// Paths that couldn't be read during the current scan (permission denied or
/// past the depth guard), itemized and capped. Empty when nothing was skipped.
List<String> scanSkippedPaths() =>
    RustLib.instance.api.crateApiScanScanSkippedPaths();

/// Home directory of the current user, the fallback scan root.
String homeDirPath() => RustLib.instance.api.crateApiScanHomeDirPath();

/// Scan root for a fresh launch: the last root the user picked, if it still
/// exists, otherwise the home directory.
String defaultScanRoot() => RustLib.instance.api.crateApiScanDefaultScanRoot();

/// Remember the picked scan root for the next launch, and add it to the
/// recent-scans list (paths only — never scan data).
void setScanRoot({required String path}) =>
    RustLib.instance.api.crateApiScanSetScanRoot(path: path);

/// Recently-scanned roots, newest first. Paths only; nothing about their
/// contents is persisted. Non-existent paths are filtered out.
List<String> recentScanRoots() =>
    RustLib.instance.api.crateApiScanRecentScanRoots();

enum FsKind {
  dir,
  file,

  /// Aggregate of one directory's files below the detail threshold.
  smallFiles,

  /// Aggregate tail of children beyond the requested limit.
  rest,
}

class FsNode {
  final PlatformInt64 id;
  final String name;
  final String path;
  final FsKind kind;

  /// On-disk (allocated) size.
  final PlatformInt64 size;

  /// Apparent (logical) size; differs from `size` for clones/sparse files.
  final PlatformInt64 logicalSize;
  final PlatformInt64 mtime;
  final PlatformInt64 fileCount;
  final PlatformInt64 dirCount;
  final PlatformInt64 itemCount;
  final PlatformInt64 childCount;
  final FsTier tier;
  final String? ruleId;
  final String? ruleName;
  final String? category;

  const FsNode({
    required this.id,
    required this.name,
    required this.path,
    required this.kind,
    required this.size,
    required this.logicalSize,
    required this.mtime,
    required this.fileCount,
    required this.dirCount,
    required this.itemCount,
    required this.childCount,
    required this.tier,
    this.ruleId,
    this.ruleName,
    this.category,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      path.hashCode ^
      kind.hashCode ^
      size.hashCode ^
      logicalSize.hashCode ^
      mtime.hashCode ^
      fileCount.hashCode ^
      dirCount.hashCode ^
      itemCount.hashCode ^
      childCount.hashCode ^
      tier.hashCode ^
      ruleId.hashCode ^
      ruleName.hashCode ^
      category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FsNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          path == other.path &&
          kind == other.kind &&
          size == other.size &&
          logicalSize == other.logicalSize &&
          mtime == other.mtime &&
          fileCount == other.fileCount &&
          dirCount == other.dirCount &&
          itemCount == other.itemCount &&
          childCount == other.childCount &&
          tier == other.tier &&
          ruleId == other.ruleId &&
          ruleName == other.ruleName &&
          category == other.category;
}

enum FsTier { none, safe, review, protected }

class ScanProgress {
  final ScanStage stage;
  final PlatformInt64 files;
  final PlatformInt64 dirs;
  final PlatformInt64 bytes;
  final PlatformInt64 errors;
  final String currentPath;

  /// Root node id, valid only when `stage == Done`.
  final PlatformInt64 rootId;

  const ScanProgress({
    required this.stage,
    required this.files,
    required this.dirs,
    required this.bytes,
    required this.errors,
    required this.currentPath,
    required this.rootId,
  });

  @override
  int get hashCode =>
      stage.hashCode ^
      files.hashCode ^
      dirs.hashCode ^
      bytes.hashCode ^
      errors.hashCode ^
      currentPath.hashCode ^
      rootId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanProgress &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          files == other.files &&
          dirs == other.dirs &&
          bytes == other.bytes &&
          errors == other.errors &&
          currentPath == other.currentPath &&
          rootId == other.rootId;
}

enum ScanStage { scanning, done, cancelled, failed }

/// How to order children in [`get_children_sorted`].
enum SortKey { size, name, items }
