// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fetch_latest_release`, `is_newer`, `mounted_volumes`, `push_dir`, `read_volume_dir`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Standard scan locations plus mounted volumes, for the landing screen. Each
/// carries an `exists` flag so the UI can grey out ones that don't apply.
List<Location> standardLocations() =>
    RustLib.instance.api.crateApiSystemStandardLocations();

/// Probe a few TCC-protected directories instead of asking the OS: there is
/// no public API to query Full Disk Access, but a successful `read_dir` on
/// any of these proves it, and exists-but-unreadable proves its absence.
FdaStatus fullDiskAccessStatus() =>
    RustLib.instance.api.crateApiSystemFullDiskAccessStatus();

/// Jump straight to System Settings → Privacy & Security → Full Disk Access.
/// No-op off macOS.
void openFullDiskAccessSettings() =>
    RustLib.instance.api.crateApiSystemOpenFullDiskAccessSettings();

/// Open the OS Trash / Recycle Bin so the user can restore trashed items.
void openTrash() => RustLib.instance.api.crateApiSystemOpenTrash();

/// Open a web link in the default browser. Only https URLs are accepted so a
/// crafted value can never launch arbitrary local handlers.
void openUrl({required String url}) =>
    RustLib.instance.api.crateApiSystemOpenUrl(url: url);

UiPrefs getUiPrefs() => RustLib.instance.api.crateApiSystemGetUiPrefs();

void setUiPrefs({required UiPrefs prefs}) =>
    RustLib.instance.api.crateApiSystemSetUiPrefs(prefs: prefs);

/// Ask GitHub for the latest published release. Only ever called from an
/// explicit "Check for updates" action — nothing phones home on its own.
Future<UpdateCheck> checkForUpdate({required String currentVersion}) => RustLib
    .instance
    .api
    .crateApiSystemCheckForUpdate(currentVersion: currentVersion);

/// Whether the app can read macOS TCC-protected locations (Mail, Safari,
/// Messages, …). Without Full Disk Access those directories fail with
/// permission errors and a home/disk scan silently under-reports.
enum FdaStatus {
  granted,
  denied,

  /// No probe location exists (or no home dir) — nothing to conclude.
  notDetermined,
}

/// A pickable scan location for the landing screen.
class Location {
  final String label;
  final String path;

  /// One of: home, desktop, documents, downloads, applications, volume.
  final String kind;
  final bool exists;

  const Location({
    required this.label,
    required this.path,
    required this.kind,
    required this.exists,
  });

  @override
  int get hashCode =>
      label.hashCode ^ path.hashCode ^ kind.hashCode ^ exists.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Location &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          path == other.path &&
          kind == other.kind &&
          exists == other.exists;
}

/// UI preferences that survive restarts (persisted in settings.json by the
/// Rust core — never scan data, never secrets).
class UiPrefs {
  /// "treemap" | "list"
  final String resultsView;

  /// "size" | "name" | "items"
  final String sortKey;
  final bool sortAscending;

  const UiPrefs({
    required this.resultsView,
    required this.sortKey,
    required this.sortAscending,
  });

  @override
  int get hashCode =>
      resultsView.hashCode ^ sortKey.hashCode ^ sortAscending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiPrefs &&
          runtimeType == other.runtimeType &&
          resultsView == other.resultsView &&
          sortKey == other.sortKey &&
          sortAscending == other.sortAscending;
}

class UpdateCheck {
  final String current;
  final String latest;
  final bool updateAvailable;
  final String releaseUrl;

  const UpdateCheck({
    required this.current,
    required this.latest,
    required this.updateAvailable,
    required this.releaseUrl,
  });

  @override
  int get hashCode =>
      current.hashCode ^
      latest.hashCode ^
      updateAvailable.hashCode ^
      releaseUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateCheck &&
          runtimeType == other.runtimeType &&
          current == other.current &&
          latest == other.latest &&
          updateAvailable == other.updateAvailable &&
          releaseUrl == other.releaseUrl;
}
